 
apiVersion: v1
kind: Service
metadata:
  name: grafana-ui 
  labels:
    app.kubernetes.io/name: grafana 
spec: 
  ports:
    - port: 3000
      targetPort: dashboard
      protocol: TCP
      name: http 
  selector:
    app.kubernetes.io/name: grafana 

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-custom
data:
  grafana.ini: |-
    [database]
    type=mysql
    host=mysql
    name=grafana
    user=root
    password=root