apiVersion: v2
appVersion: "1.18.0"
description: A Helm chart for prometheus pgbouncer-exporter
name: prometheus-pgbouncer-exporter
version: 0.1.0
home: https://github.com/prometheus-community/pgbouncer_exporter
sources:
- https://github.com/prometheus-community/pgbouncer_exporter
keywords:
- pgbouncer
- prometheus
- exporter
maintainers:
- email: stewart.shea@gmail.com
  name: stewartshea
type: application
dependencies:
- name: postgresql
  version: "~12.2.2"
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
