apiVersion: v1
version: 1.0.0
dependency:
  - name: alertmanager
    version: 0.24.*
    repository: https://prometheus-community.github.io/helm-charts
    condition: alertmanager.enabled
  - name: kube-state-metrics
    version: 4.30.*
    repository: https://prometheus-community.github.io/helm-charts
    condition: kube-state-metrics.enabled
  - name: prometheus-node-exporter
    version: 4.8.*
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-node-exporter.enabled
  - name: prometheus-pushgateway
    version: 2.0.*
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus-pushgateway.enabled
